### PR TITLE
Add `advise_range` for unix

### PR DESCRIPTION
**Pull request by ho-229**
#68

### CODE REVIEW

**Comment by adamreichold** [comment]
I think it would be good to at least include the requirement that `offset` is page-aligned in the doc comments (even though this is mentioned again the man page).

**Comment by ho-229** [comment]
You are right, not page-aligned will cause EINVAL.

**Comment by RazrFalcon** [comment]
Looks like `cargo fmt` doesn't like trailing spaces. Please remove them. Or simply run `cargo fmt` before commit.

**Comment by RazrFalcon** [comment]
Thanks!

**Pull request merged**
