### PR TITLE
Returning error if offset doesn't fit into libc::off_t.

### PR DESCRIPTION
**Pull request by lvella**
Slightly improves the situation of issue #85.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
I guess the `map_offset` should be updated to `#[should_panic]` on 32bit Linux.

**Comment by adamreichold** [comment]
I just noticed that libc actually defines [`mmap64`](https://docs.rs/libc/latest/libc/fn.mmap64.html) taking `off64_t`. I think we should just use that function and fix this for good.

**Comment by RazrFalcon** [comment]
@adamreichold Looks like it's not available for `musl`? And requires `_FILE_OFFSET_BITS` flag check?

**Comment by adamreichold** [comment]
> Looks like it's not available for `musl`?

The [libc sources](https://docs.rs/libc/latest/src/libc/unix/linux_like/mod.rs.html#1784) say

> // * musl has 64-bit versions only so aliases the LFS64 symbols to the standard ones

> And requires `_FILE_OFFSET_BITS` flag check?

I though this macro only controls whether these 64-bit wide interface replace the default interfaces or stay add-ons? But they are always available as add-ons (for glibc)?

In any case, I'd say it would be preferable to use `#[cfg(..)]` to make this work on those platforms where it can and fallback to `try_into` otherwise.

**Comment by RazrFalcon** [comment]
>The [libc sources](https://docs.rs/libc/latest/src/libc/unix/linux_like/mod.rs.html#1784) say

I wasn't able to understand what they mean. But I would assume that `mmap64` isn't available in `musl` and we have to use `mmap`, which should already support 64bit offset?

I will try adding musl target to CI.

**Comment by adamreichold** [comment]
> I haven't been able to understand what they mean. But I would assume that mmap64 isn't available in musl and we have to use mmap, which should already support 64bit offset?

Yes, my understanding is that Musl v1.2+ on 32-bit platforms has `mem::size_of::<off_t>() == 8` and hence this problem does not affect it and we can just continue to call `mmap`. It is only Glibc on 32-bit platforms which is problematic as per the OP.

**Comment by adamreichold** [comment]
Relevant part of Musl FAQ: https://wiki.musl-libc.org/faq.html#Q:-Do-I-need-to-define-%3Ccode%3E_LARGEFILE64_SOURCE%3C/code%3E-to-get-64bit-%3Ccode%3Eoff_t%3C/code%3E?

**Comment by lvella** [comment]
The logic could be: use `mmap` if `off_t` is 64 bits, use `mmap64` if available and `off_t` is less than 64 bits, otherwise use `mmap` with the overflow runtime check of this PR.

Problem is, I have no idea how to do that. I tried detecting if `mmap64` is available in a build script using crate [autocfg](https://crates.io/crates/autocfg/1.1.0), but I could not make it use `libc` in the test built files.

**Comment by RazrFalcon** [comment]
@lvella Too complicated. Let's try using `mmap64` for now and see how it will go.

**Pull request closed without merging**
