### PR TITLE
Use `u32::MAX` instead of deprectated `u32::max_value()`

### PR DESCRIPTION
**Pull request by LingMan**

### CODE REVIEW

**Comment by LingMan** [comment]
Oh, the `MAX` constants were only introduced with Rust 1.43 and the current MSRV is 1.36. On one hand it's not an important change, on the other hand 1.43 is almost 2.5 years old at this point.
Let me know if you'd be ok with bumping the MSRV.

**Comment by adamreichold** [comment]
Personally, I don't think this particular change is a good reason to bump MSRV. We can make it when we do bump MSRV for another more pressing reason.

**Comment by LingMan** [comment]
You're right. This change by itself doesn't warrant a MSRV bump. The question is more "How old of a compiler do we still want to think about?". For me personally anything over a year or so would require a strong justification.

PS: libc (which you depend on) is also [discussing](https://github.com/rust-lang/libs-team/issues/72) adopting a MSRV policy. There's no decision yet, but 2.5 years would be at the very conservative end of what has been proposed so far.

**Comment by RazrFalcon** [comment]
Couldn't we simply use `std::u32::MAX`?

**Comment by LingMan** [comment]
That's also deprecated, so nothing would be gained.

**Comment by RazrFalcon** [comment]
This change is not important enough to break MSRV.

**Pull request closed without merging**
